import "./scripts/settings.js"
import "./scripts/capitalization.js"
import "./scripts/themes.js"
import "./scripts/typesetting.js"
import "./scripts/guide-rulers.js"
import "./scripts/offline-availability.js"
import "./scripts/register-sw.js"
