on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: build/build.bash
      - uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{secrets.neocities_token}}
          cleanup: true
